version: '2'
services:
  mysql:
    container_name: mysql_migrate
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --max_allowed_packet=32505856 
  cassandra:
    container_name: cassandra_migrate
    build: ./cassandra
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
